export interface Country {
  code: string;
  nameFr: string;
  nameEn: string;
}

export const COUNTRIES: Country[] = [
  { code: 'CM', nameFr: 'Cameroun', nameEn: 'Cameroon' },
  { code: 'DZ', nameFr: 'Algérie', nameEn: 'Algeria' },
  { code: 'AO', nameFr: 'Angola', nameEn: 'Angola' },
  { code: 'BJ', nameFr: 'Bénin', nameEn: 'Benin' },
  { code: 'BW', nameFr: 'Botswana', nameEn: 'Botswana' },
  { code: 'BF', nameFr: 'Burkina Faso', nameEn: 'Burkina Faso' },
  { code: 'BI', nameFr: 'Burundi', nameEn: 'Burundi' },
  { code: 'CV', nameFr: 'Cap-Vert', nameEn: 'Cape Verde' },
  { code: 'CF', nameFr: 'Centrafrique', nameEn: 'Central African Republic' },
  { code: 'KM', nameFr: 'Comores', nameEn: 'Comoros' },
  { code: 'CG', nameFr: 'Congo', nameEn: 'Congo' },
  { code: 'CD', nameFr: 'Congo (RDC)', nameEn: 'Congo (DRC)' },
  { code: 'CI', nameFr: "Côte d'Ivoire", nameEn: "Côte d'Ivoire" },
  { code: 'DJ', nameFr: 'Djibouti', nameEn: 'Djibouti' },
  { code: 'EG', nameFr: 'Égypte', nameEn: 'Egypt' },
  { code: 'GQ', nameFr: 'Guinée équatoriale', nameEn: 'Equatorial Guinea' },
  { code: 'ER', nameFr: 'Érythrée', nameEn: 'Eritrea' },
  { code: 'SZ', nameFr: 'Eswatini', nameEn: 'Eswatini' },
  { code: 'ET', nameFr: 'Éthiopie', nameEn: 'Ethiopia' },
  { code: 'GA', nameFr: 'Gabon', nameEn: 'Gabon' },
  { code: 'GM', nameFr: 'Gambie', nameEn: 'Gambia' },
  { code: 'GH', nameFr: 'Ghana', nameEn: 'Ghana' },
  { code: 'GN', nameFr: 'Guinée', nameEn: 'Guinea' },
  { code: 'GW', nameFr: 'Guinée-Bissau', nameEn: 'Guinea-Bissau' },
  { code: 'KE', nameFr: 'Kenya', nameEn: 'Kenya' },
  { code: 'LS', nameFr: 'Lesotho', nameEn: 'Lesotho' },
  { code: 'LR', nameFr: 'Libéria', nameEn: 'Liberia' },
  { code: 'LY', nameFr: 'Libye', nameEn: 'Libya' },
  { code: 'MG', nameFr: 'Madagascar', nameEn: 'Madagascar' },
  { code: 'MW', nameFr: 'Malawi', nameEn: 'Malawi' },
  { code: 'ML', nameFr: 'Mali', nameEn: 'Mali' },
  { code: 'MR', nameFr: 'Mauritanie', nameEn: 'Mauritania' },
  { code: 'MU', nameFr: 'Maurice', nameEn: 'Mauritius' },
  { code: 'MA', nameFr: 'Maroc', nameEn: 'Morocco' },
  { code: 'MZ', nameFr: 'Mozambique', nameEn: 'Mozambique' },
  { code: 'NA', nameFr: 'Namibie', nameEn: 'Namibia' },
  { code: 'NE', nameFr: 'Niger', nameEn: 'Niger' },
  { code: 'NG', nameFr: 'Nigeria', nameEn: 'Nigeria' },
  { code: 'RW', nameFr: 'Rwanda', nameEn: 'Rwanda' },
  { code: 'ST', nameFr: 'Sao Tomé-et-Príncipe', nameEn: 'São Tomé and Príncipe' },
  { code: 'SN', nameFr: 'Sénégal', nameEn: 'Senegal' },
  { code: 'SC', nameFr: 'Seychelles', nameEn: 'Seychelles' },
  { code: 'SL', nameFr: 'Sierra Leone', nameEn: 'Sierra Leone' },
  { code: 'SO', nameFr: 'Somalie', nameEn: 'Somalia' },
  { code: 'ZA', nameFr: 'Afrique du Sud', nameEn: 'South Africa' },
  { code: 'SS', nameFr: 'Soudan du Sud', nameEn: 'South Sudan' },
  { code: 'SD', nameFr: 'Soudan', nameEn: 'Sudan' },
  { code: 'TZ', nameFr: 'Tanzanie', nameEn: 'Tanzania' },
  { code: 'TG', nameFr: 'Togo', nameEn: 'Togo' },
  { code: 'TN', nameFr: 'Tunisie', nameEn: 'Tunisia' },
  { code: 'UG', nameFr: 'Ouganda', nameEn: 'Uganda' },
  { code: 'ZM', nameFr: 'Zambie', nameEn: 'Zambia' },
  { code: 'ZW', nameFr: 'Zimbabwe', nameEn: 'Zimbabwe' },
  { code: 'FR', nameFr: 'France', nameEn: 'France' },
  { code: 'BE', nameFr: 'Belgique', nameEn: 'Belgium' },
  { code: 'CA', nameFr: 'Canada', nameEn: 'Canada' },
  { code: 'CH', nameFr: 'Suisse', nameEn: 'Switzerland' },
  { code: 'US', nameFr: 'États-Unis', nameEn: 'United States' },
  { code: 'GB', nameFr: 'Royaume-Uni', nameEn: 'United Kingdom' },
  { code: 'DE', nameFr: 'Allemagne', nameEn: 'Germany' },
  { code: 'ES', nameFr: 'Espagne', nameEn: 'Spain' },
  { code: 'IT', nameFr: 'Italie', nameEn: 'Italy' },
  { code: 'PT', nameFr: 'Portugal', nameEn: 'Portugal' },
  { code: 'BR', nameFr: 'Brésil', nameEn: 'Brazil' },
  { code: 'CN', nameFr: 'Chine', nameEn: 'China' },
  { code: 'IN', nameFr: 'Inde', nameEn: 'India' },
  { code: 'JP', nameFr: 'Japon', nameEn: 'Japan' },
];
